Store/Store/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Store.Models
{
    public class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
    }
}

Store/Store/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Store.Models
{
    public class Product
    {
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string ProductDescription { get; set; }
        public int ProductID { get; set; }
    }
}

Store/Store/ViewModels/ShoppingIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Store.Models;

namespace Store.ViewModels
{
    public class ShoppingIndexViewModel
    {
        public Customer Customer { get; set; }
        public List<Product> Products { get; set; }
    }
}

Store/Store/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Store/Store/Controllers/ShoppingController.cs
using Store.Models;
using Store.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.Controllers
{
    public class ShoppingController : Controller
    {
        // GET: Shopping
        public ActionResult Index()
        {
            ShoppingIndexViewModel model = new ShoppingIndexViewModel();
            model.Products = GetProducts();
            model.Customer = new Customer();
            model.Customer.FirstName = "Craig";
            model.Customer.LastName = "Campbell";
            return View(model);
        }

        public ActionResult ProductDetail(int? id)
        {
            if (id != null)
            {
                Product model = GetProducts().Where(p => p.ProductID == id).First();
                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }
            
        }

        private List<Product> GetProducts()
        {
            List<Product> products = new List<Product>();
            products.Add(new Product
            {
                ProductName = "Beard Wax",
                ProductPrice = "$5.00",
                ProductDescription = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.",
                ProductID = 1
            });

            products.Add(new Product
            {
                ProductName = "Tree Axe",
                ProductPrice = "$25.00",
                ProductDescription = "Ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.",
                ProductID = 2
            });

            products.Add(new Product
            {
                ProductName = "Flannel Shirt",
                ProductPrice = "$45.00",
                ProductDescription = "Solor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.",
                ProductID = 3
            });

            products.Add(new Product
            {
                ProductName = "Suspenders",
                ProductPrice = "$8.50",
                ProductDescription = "Consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.",
                ProductID = 4
            });

            return products;
        }
    }
}

Store/Store/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h2>Welcome to My Store</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <h4>Column 1</h4>
            <p>@Html.ActionLink("Tincidunt integer eu augue", "Index", "Shopping") augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>
        </div>
        <div class="col-xs-6">
            <h4>Column 2</h4>
            <p><a href="@Url.Action("Index", "Shopping")">Tincidunt integer eu augue augue</a> nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>
        </div>
    </div>
</div>

Store/Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "Shopping")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Store/Store/Views/Shopping/Index.cshtml
@model Store.ViewModels.ShoppingIndexViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Shopping</h2>
<p>Welcome, @Model.Customer.FirstName @Model.Customer.LastName</p>
<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>

<div class="row products">

    @foreach (var product in Model.Products)
    {
        <div class="col-xs-6 product">
            <div class="well">
                <h4>@product.ProductName</h4>
                <p><strong>@product.ProductPrice</strong></p>
                <p>@product.ProductDescription</p>
                @Html.ActionLink("Learn More", "ProductDetail",
                    new { id = product.ProductID },
                    new { @class = "btn btn-primary" })
                </div>
            </div>
    }

</div>

Store/Store/Views/Shopping/ProductDetail.cshtml
@model Store.Models.Product

@{
    ViewBag.Title = "ProductDetail";
}

<h2>@Model.ProductName</h2>
<p><strong>@Model.ProductPrice</strong></p>
<p>@Model.ProductDescription</p>
<a href="#" class="btn btn-lg btn-default">Add to Cart</a>
<a href="#" class="btn btn-lg btn-default">Checkout</a>